### PR TITLE
Pink border amend

### PR DESCRIPTION
**Pull request by KimberleyCook**
**_AGAIN DO NOT LOOK AT TODAY!!**_

This took me way longer to figure out then it should've and initally I completely over-engineered this in my head to the point where I was looking at css masking and clipping.

Anyway, a fix for the pink border.

After discussion with Matt W the border is now positioned around the window of your device not the content of the side.

### CODE REVIEW

**Comment by thomasdigby** [comment]
_YOU CAN'T STOP ME_

**Comment by KimberleyCook** [comment]
screen shot 2016-08-29 at 16 56 22

New border on homepage!

**Comment by thomasdigby** [comment]
Woah nice, good job! 👏

**Comment by thomasdigby** [comment]
Alright, a couple of things I think we need to look at:
- [x] Pointer-events is [_suprisingly_](http://caniuse.com/#feat=pointer-events) well supported, but it doesn't have support in ie 8/9/10 and for those browsers the overlay will block any interaction with the page. I'm not sure (bar feature testing) what we can do about this?
- [x] Border-image itself is [not](http://caniuse.com/#search=border%20image) super well supported, what's our fallback state? 
- [x] The border is not rendering a consistent line-width at the moment, I think the linear-gradient is calculating over sub-pixels which gives us the thick/thin/thick/thin look. Can we replace this with the SVG from before?
- [x] The designs indicate that the line is hidden on mobile viewports, can you add that breakpoint back in

**Comment by thomasdigby** [comment]
@KimberleyCook take a look and let me know what you think.

**Pull request merged**
