### PR TITLE
Added show/hide functionality for product cta

### PR DESCRIPTION
**Pull request by thomasdigby**

### CODE REVIEW

**Comment by thomasdigby** [comment]
The conflicts are caused by the production files, everything else is a-ok.

**Comment by thomasdigby** [comment]
This PR hides the "BUY HERE" button on mobile and shows it when scrolling past the main image. It hides the button again when scrolling to the "You may also love" section.

**Comment by thomasdigby** [comment]
👍

**Comment by KimberleyCook** [comment]
Thank you :) all works. Merging.

**Pull request merged**
