### PR TITLE
Added new SVG logo, reworked layout, other stuff

### PR DESCRIPTION
**Pull request by thomasdigby**
I don't know why I did all of this, I got carried away when I added the SVG. One more task off your list tomorrow I guess, have a coffee break on me!

### CODE REVIEW

**Comment by KimberleyCook** [comment]
This re-working no longer fits the designs when it did before. 

Also still not sure we should have Best Beauty as a hard coded SVG when the font being used for it is Raleway, which is also used throughout the whole site. Going forward with this project with a hard coded SVG of Best Beauty will not work, before it was pulling in the product collection title. So completely re-useable.

Would be intrigued to know other people's thoughts on this?

**Comment by thomasdigby** [comment]
What changes have been made to the designs since yesterday?

I'm also eager to hear people's thoughts on the logo, I think an SVG is absolutely required. There are so many variables to rendering a font on the web cross browser (size, height, weight, font features etc.) and that's assuming the font's loaded in the first place, which the recent rise of script blockers means we can't rely on.

**Comment by KimberleyCook** [comment]
But we can't hard code an SVG for every product collection going forward, plus yes it will render slightly different across browsers but it would be inline with whole site as it's all Raleway.

**Comment by thomasdigby** [comment]
I understand that, but when the time comes for another product collection the likelihood is that they'll create a new logo. Do we know when the next product collection will be created?

**Comment by KimberleyCook** [comment]
So you'll have a different landing page for every product collection? As the plan with best beauty is to continue adding products on a regular basis.

**Comment by thomasdigby** [comment]
I didn't know the plan for the extra product collections so I guess if they're adding collections fairly regularly then a font might be a better solution? I'm still a little concerned due to the aforementioned issues but we can catch up about it next week. 🙂

**Comment by KimberleyCook** [comment]
I do think the Stylist logo should be an SVG by the way :) just not the words Best Beauty or By

**Comment by ecoad** [comment]
Future proofing the Product Collection front-end is I think fruitless, just focus on making the Best Beauty look as a best and beautiful as can be! Stick with the SVG logo for now.

**Pull request merged**
