### PR TITLE
Updated flex-layout to align items to a stricter grid

### PR DESCRIPTION
**Pull request by thomasdigby**

### CODE REVIEW

**Comment by KimberleyCook** [comment]
Is this now right @thomasdigby ?

screen shot 2016-09-01 at 18 54 49

**Comment by thomasdigby** [comment]
Yep! What do you think? (Maybe not, what browser?)

**Comment by KimberleyCook** [comment]
This is Chrome

**Comment by thomasdigby** [comment]
What version? On OSX I assume?

**Comment by thomasdigby** [comment]
Ohhh, it's probably because you only have 3 categories and I'm doing some `nth-last-child` stuff to target the last 2. It's working when the 8 categories are in.

**Comment by KimberleyCook** [comment]
Hmm I don't fully understand what this does. And feel like going on the assumption that they'll always be 8 items in the category may not be the best way to do those styles.

**Comment by thomasdigby** [comment]
Merging as we have 8 for live, lets review on Tuesday.

**Pull request merged**
