### PR TITLE
SEO updates

### PR DESCRIPTION
**Pull request by thomasdigby**

### CODE REVIEW

**Comment by ecoad** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9KmVc99b&#x2F;122-high-prioirty-easy-seo-work"> High prioirty&#x2F;easy SEO work</a>

**Comment by ecoad** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9KmVc99b&#x2F;122-high-prioirty-easy-seo-work"> High prioirty&#x2F;easy SEO work</a>

**Comment by thomasdigby** [comment]
@jonsherrard @KimberleyCook We might need to push this through early this week.

**Review by ecoad — APPROVED** [review]
This looks great to me.

**Pull request merged**
