### PR TITLE
tweaked quote style

### PR DESCRIPTION
**Pull request by KimberleyCook**
- Tweaked the author styles on the quote
- Also formatted the file to make it more readable as there wasn't gaps between the classes, made it hard to read

### CODE REVIEW

**Comment by thomasdigby** [comment]
It's probably not wise to make any updates to the design without either of the two Matts taking a look.

**Comment by KimberleyCook** [comment]
I messaged Matt W beforehand

**Comment by thomasdigby** [comment]
Ah ok, I think I'd still prefer to park the design amends until we can get Phare and Wheeler to agree on changes together. @ecoad what are your thoughts?

Also, I know the design of the quote/author was a sticking point for Matt Phare when we went through the site, so I'm hesitant to change it.

**Comment by ecoad** [comment]
Yes, all design review to happen with the Matts. Which is Monday, not far now. Can't wait for this sucker to look super nice.

**Pull request closed without merging**
